# nixpacks.toml (place at repo root)

[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "cd client && npm install --legacy-peer-deps",
  "cd server && npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
