# nixpacks.toml (place at repo root)

[phases.setup]
# Pin Node 18 for build/run
nixpkgs = ["nodejs_18"]

[phases.install]
# Install root deps (which triggers workspaces via npm)
# We need dev deps for TypeScript/Vite builds, so DO NOT omit dev
cmds = ["npm ci"]

[phases.build]
# Builds client then server via your root "build" script
cmds = ["npm run build"]

[start]
# Starts your compiled server which also serves the Vite build
cmd = "npm start"
